spring.application.name=inventarios

#Conexion a mysql - usa variables de entorno para docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/inventario_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1111}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Config patron de log
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
# configurar nivel de log
loggin.level.root=INFO
#configurar por niveles, por paquetes
#loggin.level.gm.invetarios=DEBUG
spring.main.banner-mode=off